<header>
    <button id="sidepanel">
        <svg x="0px" y="0px" viewBox="0 0 337.792 337.792">
            <path d="M337.792,134.824l-130.824,99.441v-52.216C117.061,173.419,30.735,207.817,0.001,302.41 C-0.337,180.728,99.895,111.781,206.968,88.488V35.382L337.792,134.824z"/>
        </svg>
    </button>
    <h2>Daymon Moss</h2>
    <h1>Full Stack Digital<br>Business Developer</h1>

    <h3>Personal info:</h3>
    <address>
        Address:<br> Kyiv, Ukraine<br>
        Email:<br> <a href="mailto:daymonmoss@gmail.com">daymonmoss@gmail.com</a><br>
        LinkedIn:<br> <a href="https://linkedin.com/in/daymonmoss" target="_blank">linkedin.com/in/daymonmoss</a>
    </address>
    <h3>Skills:</h3>
    <ul>
        <li>Develop web-sites and web-apps</li>
        <li>SEO Optimisation</li>
        <li>PPC Setup</li>
        <li>Data Science</li>
    </ul>
    <h3>Software:</h3>
    <ul>
        <li>Windows cmd</li>
        <li>Linux (Ubuntu, Centos) bash</li>
        <li>Apache</li>
        <li>Nginx</li>
        <li>MySQL (MariaDB)</li>
        <li>Npm</li>
        <li>Webpack</li>
        <li>Git</li>
        <li>Composer</li>
        <li>ReactJS, mobx</li>
        <li>VueJS</li>
        <li>Yii2</li>
        <li>Symfony</li>
        <li>Magento 2</li>
        <li>Opencart</li>
        <li>Wordpress</li>
        <li>ModX</li>
    </ul>
    <h3>Languages:</h3>
    <ul>
        <li>HTML</li>
        <li>CSS: SCSS</li>
        <li>JavaScript: TypeScript, JSX, TSX</li>
        <li>PHP</li>
        <li>SQL</li>
        <li>Python</li>
        <li>Ukrainian</li>
        <li>Russian</li>
        <li>English</li>
        <li>Romanian</li>
    </ul>
</header>
<main>
    <p>
        Computer Systems Engineer with over 10 years of experience specialising of hardware, software and online
        marketing for much companies end peoples.
        I can implement effective IT Strategies at local and global levels.
        My greatest strength is business awareness, which enables me to permanently streamline infrastructure and
        applications.
        Striving to leverage my IT management skills to achieve the best result for the shortest possible time.
    </p>
    <section>
        <hr>
        <h4>Experience</h4>
        <div class="container">
            <div class="row">
                <div class="w-35">
                    <div class="row highlight">
                        <div class="w-50px"><b>Start:</b></div>
                        <div>January 2019</div>
                    </div>
                    <div class="row highlight">
                        <div class="w-50px"><b>End:</b></div>
                        <div>January 2020</div>
                    </div>
                </div>
                <div class="w-65">

                    <div class="row highlight">
                        <div class="w-80px"><b>Company:</b></div>
                        <div>Victoria LLC</div>
                    </div>
                    <div class="row highlight">
                        <div class="w-80px"><b>In:</b></div>
                        <div>Moscow, Russia</div>
                    </div>
                    <div class="row">
                        <div class="w-80px"><b>Brands:</b></div>
                        <div class="w-100">
                            <div class="row highlight">
                                <div class="w-200px">Relieffo</div>
                                <div><a href="https://relieffo.ru" target="_blank">https://relieffo.ru</a></div>
                            </div>
                            <div class="row highlight">
                                <div class="w-200px">Autorender(Cloudsgoods)</div>
                                <div><a href="https://cloudsgoods.com"
                                        target="_blank">https://cloudsgoods.com</a></div>
                            </div>
                        </div>
                    </div>
                    <ul>
                        <li class="highlight">Created Relieffo online store from CMS Opencart</li>
                        <li class="highlight">Customise template and modules for https://relieffo.ru on CMS
                            Opencart
                        </li>
                        <li class="highlight">Created several promo landing pages for Relieffo advertise
                            campaign
                        </li>
                        <li class="highlight">Autorender(Cloudsgoods) service Progect Managment</li>
                        <li class="highlight">Collaboration with designers, freelance developers, copywriters
                        </li>
                        <li class="highlight">Frontend development Autorender(Cloudsgoods) on VueJs</li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="container">
            <div>
                <div class="row">
                    <div class="w-35">
                        <div class="row highlight">
                            <div class="w-50px"><b>Start:</b></div>
                            <div>April 2018</div>
                        </div>
                        <div class="row highlight">
                            <div class="w-50px"><b>End:</b></div>
                            <div>December 2018</div>
                        </div>
                    </div>
                    <div class="w-65">
                        <div class="row highlight">
                            <div class="w-80px"><b>Company:</b></div>
                            <div>Immergity LLC</div>
                        </div>
                        <div class="row highlight">
                            <div class="w-80px"><b>In:</b></div>
                            <div>Moscow, Russia</div>
                        </div>
                        <div class="row">
                            <div class="w-80px"><b>Brands:</b></div>
                            <div class="w-100">
                                <div class="row highlight">
                                    <div class="w-200px">Immergity</div>
                                    <div><a href="https://immergity.com" target="_blank">https://immergity.com</a></div>
                                </div>
                                <div class="row highlight">
                                    <div class="w-200px">INPROJECT Architects</div>
                                    <div><a href="http://in-ar.ru" target="_blank">http://in-ar.ru</a></div>
                                </div>
                            </div>
                        </div>
                        <ul>
                            <li class="highlight">Created MVP React/Mobx Application widget for construction companies
                                <a href="http://plans-app-test.herokuapp.com/">http://plans-app-test.herokuapp.com/</a>
                            </li>
                            <li class="highlight">Customise Imergity website on CMS Wordpress</li>
                            <li class="highlight">Content management INPROJECT Architect website on custom CMS</li>
                        </ul>
                    </div>
                </div>
            </div>
            <div>
                <div class="row">
                    <div class="w-35">
                        <div class="row highlight">
                            <div class="w-50px"><b>Start:</b></div>
                            <div>September 2017</div>
                        </div>
                        <div class="row highlight">
                            <div class="w-50px"><b>End:</b></div>
                            <div>April 2018</div>
                        </div>
                    </div>
                    <div class="w-65">
                        <div class="row highlight">
                            <div class="w-80px"><b>Company:</b></div>
                            <div>Elite Group LLC</div>
                        </div>
                        <div class="row highlight">
                            <div class="w-80px"><b>In:</b></div>
                            <div>Korolev, Moscow state, Russia</div>
                        </div>
                        <div class="row">
                            <div class="w-80px"><b>Brand:</b></div>
                            <div class="w-100">
                                <div class="row highlight">
                                    <div class="w-200px">Santehnika Tut</div>
                                    <div><a href="https://santehnika-tut.ru"
                                            target="_blank">https://santehnika-tut.ru</a></div>
                                </div>
                            </div>
                        </div>
                        <ul>
                            <li class="highlight">Content SEO optimisation plumbing online store categories,
                                subcategories meta tags, keywords
                            </li>
                            <li class="highlight">Develop Technical Tasks on category and subcategory reviews for
                                copywriters
                            </li>
                            <li class="highlight">Collaboration with copywriters</li>
                            <li class="highlight">Web Analytics</li>
                        </ul>
                    </div>
                </div>
            </div>
            <div>
                <div class="row">
                    <div class="w-35">
                        <div class="row highlight">
                            <div class="w-50px"><b>Start:</b></div>
                            <div>March 2017</div>
                        </div>
                        <div class="row highlight">
                            <div class="w-50px"><b>End:</b></div>
                            <div>September 2017</div>
                        </div>
                    </div>
                    <div class="w-65">
                        <div class="row highlight">
                            <div class="w-80px"><b>Company:</b></div>
                            <div>Balakkom LLC <a href="https://balakkom.com/main-page" target="_blank">https://balakkom.com</a>
                            </div>
                        </div>
                        <div class="row highlight">
                            <div class="w-80px"><b>In:</b></div>
                            <div>Chernivtsi, Chernivtsi state, Ukraine</div>
                        </div>
                        <div class="row">
                            <div class="w-80px"><b>Brands:</b></div>
                            <div class="w-100">
                                <div class="row highlight">
                                    <div class="w-200px">TEP</div>
                                    <div><a href="https://tep.ua" target="_blank">https://tep.ua</a></div>
                                </div>
                                <div class="row highlight">
                                    <div class="w-200px">Ego Style</div>
                                    <div><a href="https://ego-style.com.ua" target="_blank">https://ego-style.com.ua</a>
                                    </div>
                                </div>
                                <div class="row highlight">
                                    <div class="w-200px">Azbuka Sna</div>
                                    <div><a href="https://azbukasna.com/" target="_blank">https://azbukasna.com/</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <ul>
                            <li class="highlight">Content SEO optimisation categories and subcategories descriptions,
                                products meta tags
                            </li>
                            <li class="highlight">Web Analytics, collect semantic core</li>
                            <li class="highlight">Develop PPC campaigns</li>
                        </ul>
                    </div>
                </div>
            </div>
            <div>
                <div class="row">
                    <div class="w-35">
                        <div class="row highlight">
                            <div class="w-50px"><b>Start:</b></div>
                            <div>February 2016</div>
                        </div>
                        <div class="row highlight">
                            <div class="w-50px"><b>End:</b></div>
                            <div>February 2017</div>
                        </div>
                    </div>
                    <div class="w-65">
                        <div class="row highlight">
                            <div class="w-80px"><b>Company:</b></div>
                            <div>AlterEGO Digital Agency <a href="https://alterego.digital/en/" target="_blank">https://alterego.digital</a>
                            </div>
                        </div>
                        <div class="row highlight">
                            <div class="w-80px"><b>In:</b></div>
                            <div>Chernivtsi, Chernivtsi state, Ukraine</div>
                        </div>
                        <div class="row">
                            <div class="w-80px"><b>Brands:</b></div>
                            <div class="w-100">
                                <div class="row highlight">
                                    <div class="w-200px">Bosco di Ciliegi</div>
                                    <div><a href="https://www.bosco.ru/eng/" target="_blank">https://bosco.ru</a></div>
                                </div>
                                <div class="row highlight">
                                    <div class="w-200px">Kubachi Shop</div>
                                    <div><a href="https://kubachishop.ru" target="_blank">https://kubachishop.ru</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <ul>
                            <li class="highlight">Bosco di Ciliegi Family online stores content SEO optimisation</li>
                            <li class="highlight">Develop Technical Tasks on category and subcategory descriptions for
                                copywriters, products meta tags
                            </li>
                            <li class="highlight">Web Analytics, semantic core collection</li>
                            <li class="highlight">PPC Advertising campaign for Kubachi Shop</li>
                        </ul>
                    </div>
                </div>
            </div>
            <div>
                <div class="row">
                    <div class="w-35">
                        <div class="row highlight">
                            <div class="w-50px"><b>Start:</b></div>
                            <div>February 2013</div>
                        </div>
                        <div class="row highlight">
                            <div class="w-50px"><b>End:</b></div>
                            <div>November 2015</div>
                        </div>
                    </div>
                    <div class="w-65">
                        <div class="row highlight">
                            <div class="w-80px"><b>Company:</b></div>
                            <div>Zabava <a href="http://zabava-bz.com/lang-en" target="_blank">http://zabava-bz.com/</a>
                            </div>
                        </div>
                        <div class="row highlight">
                            <div class="w-80px"><b>In:</b></div>
                            <div>Chernivtsi, Chernivtsi state, Ukraine</div>
                        </div>
                        <ul>
                            <li class="highlight">Develop schemas and 3D Models of Printed Circuit Boards</li>
                            <li class="highlight">Create Components Specifications for Printed Circuit Boards</li>
                            <li class="highlight">Assembly Developed Printed Circuit Boards for games and cryptomining
                                industry
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <hr>
    </section>
    <section>
        <hr>
        <h4>Education</h4>
        <div class="container">
            <div class="row">
                <div class="w-50">

                    <div>
                        <div>
                            <div class="row highlight">
                                <div class="w-120px"><b>Graduation:</b></div>
                                <div>Bachelor of Computer Engineering</div>
                            </div>
                        </div>
                        <div>
                            <div class="row highlight">
                                <div class="w-120px"><b>Year:</b></div>
                                <div>2013</div>
                            </div>
                        </div>
                        <div>
                            <div class="row highlight">
                                <div class="w-120px"><b>Organisation:</b></div>
                                <div>Lviv Polytechnic State University <a href="https://lpnu.ua/en/cas" target="_blank">https://lpnu.ua</a></div>
                            </div>
                        </div>

                    </div>
                    <div>

                        <div>
                            <div class="row highlight">
                                <div class="w-120px"><b>Graduation:</b></div>
                                <div>Junior Specialist of Computer Engineering</div>
                            </div>
                        </div>
                        <div>
                            <div class="row highlight">
                                <div class="w-120px"><b>Year:</b></div>
                                <div>2010</div>
                            </div>
                        </div>
                        <div>
                            <div class="row highlight">
                                <div class="w-120px"><b>Organisation:</b></div>
                                <div>Chernivtsi Industrial College <a href="https://chic.cv.ua/obslugovuvannya-kompyuternih-sistem-i/" target="_blank">https://chic.cv.ua</a></div>
                            </div>
                        </div>

                    </div>


                </div>
                <div class="w-50">
                    <div>

                        <div>
                            <div class="row highlight">
                                <div class="w-120px"><b>Graduation:</b></div>
                                <div>Magento2 Backend Development Training Program</div>
                            </div>
                        </div>
                        <div>
                            <div class="row highlight">
                                <div class="w-120px"><b>Year:</b></div>
                                <div>2021</div>
                            </div>
                        </div>
                        <div>
                            <div class="row highlight">
                                <div class="w-120px"><b>Organisation:</b></div>
                                <div>
                                    <div>Overdose Digital Agency <a href="https://odtech.club/" target="_blank">https://odtech.club/</a></div>
                                </div>
                            </div>
                        </div>

                    </div>

                    <div>

                        <div>
                            <div class="row highlight">
                                <div class="w-120px"><b>Graduation:</b></div>
                                <div>Basic online store on Symfony</div>
                            </div>
                        </div>
                        <div>
                            <div class="row highlight">
                                <div class="w-120px"><b>Year:</b></div>
                                <div>2020</div>
                            </div>
                        </div>
                        <div>
                            <div class="row highlight">
                                <div class="w-120px"><b>Application:</b></div>
                                <div>
                                    <div>YouTube</div>
                                </div>
                            </div>
                        </div>

                    </div>

                    <div>

                        <div>
                            <div class="row highlight">
                                <div class="w-120px"><b>Graduation:</b></div>
                                <div>Basic web application on Yii2</div>
                            </div>
                        </div>
                        <div>
                            <div class="row highlight">
                                <div class="w-120px"><b>Year:</b></div>
                                <div>2020</div>
                            </div>
                        </div>
                        <div>
                            <div class="row highlight">
                                <div class="w-120px"><b>Application:</b></div>
                                <div>
                                    <div>YouTube</div>
                                </div>
                            </div>
                        </div>

                    </div>

                    <div>

                        <div>
                            <div class="row highlight">
                                <div class="w-120px"><b>Graduation:</b></div>
                                <div>Basic Php</div>
                            </div>
                        </div>
                        <div>
                            <div class="row highlight">
                                <div class="w-120px"><b>Year:</b></div>
                                <div>2019</div>
                            </div>
                        </div>
                        <div>
                            <div class="row highlight">
                                <div class="w-120px"><b>Applications:</b></div>
                                <div>
                                    <div>Codecademy <a href="https://www.codecademy.com/catalog/language/php" target="_blank">https://www.codecademy.com/catalog/language/php</a></div>
                                    <div>Sololearn <a href="https://www.sololearn.com/learning/1059" target="_blank">https://www.sololearn.com/learning/1059</a></div>
                                </div>
                            </div>
                        </div>

                    </div>

                    <div>

                        <div>
                            <div class="row highlight">
                                <div class="w-120px"><b>Graduation:</b></div>
                                <div>Basic React</div>
                            </div>
                        </div>
                        <div>
                            <div class="row highlight">
                                <div class="w-120px"><b>Year:</b></div>
                                <div>2018</div>
                            </div>
                        </div>
                        <div>
                            <div class="row highlight">
                                <div class="w-120px"><b>Applications:</b></div>
                                <div>
                                    <div>Codecademy <a href="https://www.codecademy.com/learn/react-101" target="_blank">https://www.codecademy.com/learn/react-101</a></div>
                                    <div>Sololearn <a href="https://www.sololearn.com/learning/1097" target="_blank">https://www.sololearn.com/learning/1097</a></div>
                                </div>
                            </div>
                        </div>


                    </div>

                    <div>

                        <div>
                            <div class="row highlight">
                                <div class="w-120px"><b>Graduation:</b></div>
                                <div>Basic JavaScript</div>
                            </div>
                        </div>
                        <div>
                            <div class="row highlight">
                                <div class="w-120px"><b>Year:</b></div>
                                <div>2018</div>
                            </div>
                        </div>
                        <div>
                            <div class="row highlight">
                                <div class="w-120px"><b>Applications:</b></div>
                                <div>
                                    <div>Codecademy <a href="https://www.codecademy.com/catalog/language/javascript" target="_blank">https://www.codecademy.com/catalog/language/javascript</a></div>
                                    <div>Sololearn <a href="https://www.sololearn.com/learning/1024" target="_blank">https://www.sololearn.com/learning/1024</a></div>
                                </div>
                            </div>
                        </div>

                    </div>

                    <div>

                        <div>
                            <div class="row highlight">
                                <div class="w-120px"><b>Graduation:</b></div>
                                <div>Online Store on CMS ModX</div>
                            </div>
                        </div>
                        <div>
                            <div class="row highlight">
                                <div class="w-120px"><b>Year:</b></div>
                                <div>2018</div>
                            </div>
                        </div>
                        <div>
                            <div class="row highlight">
                                <div class="w-120px"><b>Application:</b></div>
                                <div>
                                    <div>YouTube</div>
                                </div>
                            </div>
                        </div>

                    </div>

                    <div>

                        <div>
                            <div class="row highlight">
                                <div class="w-120px"><b>Graduation:</b></div>
                                <div>Basic Python</div>
                            </div>
                        </div>
                        <div>
                            <div class="row highlight">
                                <div class="w-120px"><b>Year:</b></div>
                                <div>2017</div>
                            </div>
                        </div>
                        <div>
                            <div class="row highlight">
                                <div class="w-120px"><b>Applications:</b></div>
                                <div>
                                    <div>Codecademy <a href="https://www.codecademy.com/catalog/language/python" target="_blank">https://www.codecademy.com/catalog/language/python</a></div>
                                    <div>Sololearn <a href="https://www.sololearn.com/learning/1073" target="_blank">https://www.sololearn.com/learning/1073</a></div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <hr>
    </section>
</main>
<button id="return">
    <svg xmlns="http://www.w3.org/2000/svg" width="54" height="54">
        <path id="up-arrow" fill="#000" fill-rule="evenodd" d="m27.16511,23.26473l5.50384,5.11581c0.38041,0.35359 0.38041,0.92536 0,1.27519l-0.91461,0.85013c-0.38041,0.35359 -0.99555,0.35359 -1.37191,0l-3.9053,-3.62245l-3.90125,3.62621c-0.38041,0.35359 -0.99555,0.35359 -1.37191,0l-0.91866,-0.85013c-0.38041,-0.35359 -0.38041,-0.92536 0,-1.27519l5.50384,-5.11581c0.38041,-0.35735 0.99555,-0.35735 1.37596,-0.00376z"/>
    </svg>
</button>

