 <h1>This is Widget Overdose Module!</h1>

<div id="element" data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": false, "multipleCollapsible": false}}'>
    <div data-role="collapsible">
        <div data-role="trigger">
            <span>Get JSON RESPONSE</span>
        </div>
    </div>
    <div data-role="content" id="jsonresponse">

        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer sit amet aliquet purus, et malesuada lorem. Quisque dapibus arcu justo, sed bibendum purus volutpat ut. Nulla accumsan interdum odio, quis dapibus magna finibus nec. Pellentesque pretium at lectus at tincidunt. Fusce et placerat enim. Ut vitae felis non nisi finibus tempus ut quis quam. Nunc ut sollicitudin metus. Morbi risus ligula, tincidunt in turpis eget, tincidunt euismod erat. Nulla ut egestas enim. Aenean at volutpat velit. Donec hendrerit nec tortor id vulputate. Sed fermentum quam volutpat, pharetra enim in, finibus purus. Maecenas imperdiet fermentum vestibulum. Suspendisse potenti. Fusce diam est, auctor in arcu a, pretium pulvinar purus. Nulla faucibus sapien id nulla malesuada venenatis.</p>
        <p>Duis vel pulvinar nisi. Sed posuere, felis ac tristique feugiat, ex orci auctor leo, et malesuada metus tellus suscipit arcu. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas malesuada ultrices est non pretium. Pellentesque dignissim tempor fringilla. Quisque malesuada nulla non scelerisque imperdiet. Pellentesque a nibh ipsum. Vestibulum sapien eros, ultrices vel efficitur sit amet, efficitur sit amet quam. Vestibulum at pellentesque turpis. Proin quis convallis ex. Cras erat arcu, imperdiet eu suscipit ut, iaculis quis orci. Nam vehicula dolor eu aliquet tempor. Morbi finibus, nisl a porta ultrices, ligula elit pharetra massa, id molestie lacus odio interdum augue. Nulla facilisi.</p>
    </div>
</div>





