<?php
/**
 * @var Overblock $block,
 **/
use Overdose\Attributes\Block\Overblock;

$viewModel = $this->getData('index.newview');
?>

   <h1>This is Attributes Overdose Module!</h1>


   <img src="<?php echo $this->getViewFileUrl('Overdose_Attributes::img/luxury1.png'); ?>" /><br><br><br>

   <?php
   echo $block->showBlock() . "<br>";
   echo $viewModel->fromViewModel() . "<br><br><br>";
   ?>

   <img src="<?php echo $this->getViewFileUrl('Overdose_Attributes::img/luxury2.png'); ?>" />
